class Config():
    DISCORD_TOKEN = '<NALEŻY_DODAĆ_WŁASNE_KLUCZE>'
    DISCORD_CLIENT_SECRET = '<WLASNY_SECRET_DISCORD>'
    TEST_SERVER_ID = ['<WLASNY_ID_SERWERA>']
    PANDASCORE_TOKEN = '<NALEŻY_DODAĆ_WŁASNE_KLUCZE>'
    PANDASCORE_BASE_URL = "https://api.pandascore.co"
